services:

  court-pipeline-build:
    build:
      context: .
      target: dev
    image: court-pipeline:${IMAGE_TAG:-latest}

  court-pipeline-run:
    image: court-pipeline:${IMAGE_TAG:-latest}
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_SECURE: false
    depends_on:
      - court-pipeline-minio
      - court-pipeline-minio-client
    volumes:
      - ./:/services/court-pipeline/
    command: tail -f /dev/null

  court-pipeline-minio:
    hostname: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  court-pipeline-minio-client:
    image: minio/mc:latest
    depends_on:
      - court-pipeline-minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing minio/boxscoresummary \
      minio/scoreboard;
      exit 0;
      "
